### ISSUE TITLE
suggestion chest infinity

### ISSUE THREAD

**Issue by SrMonsterYT** [lijinhong11/SfBetterChests#1]
you could create the infinite trunk, similar to the wildchests or epichoppers plugin

wildchests: https://prnt.sc/C8H-RVbT0wfy ( estoque = stock )

link: https://github.com/BG-Software-LLC/WildChests

or use the same mechanics as the infinite storage of the networks, to create an infinite trunk, where it will only have 1 slot and infinite capacity.

**Comment by lijinhong11** [comment]
Completed in build 6
